[package]
name = "nero_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
nero_core = { path = "../nero_core" }
nero_requests = { path = "../nero_requests" }
tokio = {workspace = true}
reqwest = {workspace = true}

[[bin]]
name = "nero"
path = "./src/main.rs"
